CREATE TABLE galpao (
    id_galpao  bigint generated by default as identity,
    nome VARCHAR(50),
    localizacao       VARCHAR(50)  NOT NULL,
    capacidade        bigint,
    motos_ocupadas   bigint,     
    primary key (id_galpao)
);

CREATE TABLE moto (
    id_moto  bigint generated by default as identity,
    placa    VARCHAR(7),
    chassi   VARCHAR(17),
    status   VARCHAR(10)  NOT NULL,
    modelo   VARCHAR(30)  NOT NULL,
    primary key (id_moto)
);


   create table usuario (
        id bigint generated by default as identity,
        img_perfil varchar(255),
        nome_perfil varchar(255),
        senha varchar(255),
        username varchar(255),
        role varchar(20),
        primary key (id)
    );